# See notes in pyzmq/meta.yaml.
{% set version = "4.3.4" %}

package:
  name: chaquopy-libzmq
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/zeromq/libzmq/releases/download/v{{ version }}/zeromq-{{ version }}.tar.gz
