{% if PY_VER == "3.8" %}
    {% set numpy_version = "1.19.5" %}
{% elif PY_VER in ["3.9", "3.10", "3.11"] %}
    {% set numpy_version = "1.23.3" %}
{% elif PY_VER == "3.12" %}
    {% set numpy_version = "1.26.2" %}
{% endif %}

{% set version = "2.1.3" %}

package:
  name: pandas
  version: "{{ version }}"

# The setuptools build still works for now, but the sdist on PyPI doesn't include a
# setup.py, and neither does the GitHub "source code" archive.
source:
  git_url: https://github.com/pandas-dev/pandas
  git_rev: v{{ version }}

build:
  number: 0

requirements:
  host:
    - python
    - numpy {{ numpy_version }}
