{% if PY_VER == "3.8" %}
    {% set numpy_version = "1.19.5" %}
{% else %}
    {% set numpy_version = "1.23.3" %}
{% endif %}

package:
  name: astropy
  version: "5.1.1"

build:
  number: 1

requirements:
  build:
    - cython 0.29.32
    - extension-helpers 1.0.0
    - setuptools-scm 7.1.0
  host:
    - numpy {{ numpy_version }}
