package:
  name: murmurhash
  version: 0.28.0

build:
  number: 11

requirements:
  build:
    # The .cpp file in the sdist isn't compatible with current Python versions, so it
    # needs to be regenerated.
    - Cython 3.0.11
