# We also maintain an older version of this package to support the Chaquopy unit tests -
# see the branch `murmurhash-0`.

package:
  name: murmurhash
  version: 0.28.0

build:
  number: 9

requirements:
  build:
    - Cython 3.0.11

    # Newer versions removed msvccompiler, and ignore CFLAGS environment variable for
    # some reason.
    - setuptools 69.0.2
