{% if PY_VER == "3.8" %}
    {% set numpy_version = "1.19.5" %}
{% else %}
    {% set numpy_version = "1.23.3" %}
{% endif %}

package:
  name: matplotlib
  version: 3.6.0

build:
  number: 0

requirements:
  host:
    - chaquopy-freetype 2.9.1
    - chaquopy-libpng 1.6.34
    - numpy {{ numpy_version }}
