{% if PY_VER == "3.8" %}
    {% set numpy_version = "1.19.5" %}
{% elif PY_VER in ["3.9", "3.10", "3.11"] %}
    {% set numpy_version = "1.23.3" %}
{% endif %}

package:
  name: scipy
  version: "1.9.3"

build:
  number: 1
  script_env:
    - SCIPY_USE_PYTHRAN=0

requirements:
  build:
    - fortran
  host:
    - chaquopy-libgfortran 4.9
    - chaquopy-openblas 0.2.20
    - numpy {{ numpy_version }}