package:
  name: scipy
  version: "1.9.3"

build:
  number: 1
  script_env:
    - SCIPY_USE_PYTHRAN=0

requirements:
  build:
    - fortran
  host:
    - chaquopy-libgfortran 4.9
    - chaquopy-openblas 0.2.20
    - numpy 1.23.3
