{% set version = "4.9.2" %}

package:
  name: chaquopy-netcdf4
  version: {{ version }}

source:
#  wget_url: ftp.unidata.ucar.edu/pub/netcdf/netcdf-{{ version }}
#  git_rev: v{{ version }}
  git_url: https://github.com/Unidata/netcdf-c.git
  git_rev: v{{ version }}

build:
  number: 1

#requirements:
#  build:
#    - numpy 1.24.2
#    - h5py 3.8.0
#    - hdf5 1.12.2
#    - cftime 1.6.2
#    - zlib 1.2.13
#  host:
#    - numpy 1.24.2
#    - numpy 1.17.4
#    - h5py 1.24.2
#    - h5py 2.10.0
#    - python
