{% if PY_VER == "3.8" %}
    {% set numpy_version = "1.19.5" %}
{% else %}
    {% set numpy_version = "1.23.3" %}
{% endif %}

package:
  name: Shapely
  version: "2.0.6"

requirements:
  host:
    - chaquopy-geos 3.8.1
    - numpy {{ numpy_version }}
