#!/bin/bash
# On Unix:      ln -s ../../hooks/pre-commit .git/hooks/pre-commit
# On Windows:   mklink /H .git\hooks\pre-commit hooks\pre-commit

result=0

exclude_re='^(hooks/pre-commit)|(product/gradle-plugin/src/main/python/pip/)'
files=$(git diff --cached --diff-filter=d --name-only | egrep -v "$exclude_re")

if [ -n "$files" ]; then
    if grep -Hn FIXME $files; then result=1; fi

    py_files=$(echo $files | tr ' ' '\n' | grep 'py$')
    if [ -n "$py_files" ]; then
        if ! flake8 $py_files; then result=1; fi
    fi
fi

exit $result
