name: Setup Python
description:

runs:
  using: composite
  steps:
    # For the default Python version, the micro version should be different to the
    # one used by the runtime, because that's required by the integration tests
    # `requires_python` and `marker_python_version`. For all other versions, we let
    # the GitHub runner pick a micro version, which will be faster because it's
    # locally cached.
    - name: Get default Python version
      id: python-default
      shell: bash
      run: |
        version="3.10"
        (
            echo "full-version=${version}.11"
            if [ $RUNNER_OS = Windows ]; then
                echo "command=py -$version"
            else
                echo "command=python$version"
            fi
        ) >> $GITHUB_OUTPUT

    - uses: actions/setup-python@v5.1.0
      with:
        # This should include all major.minor versions supported by the runtime, plus
        # OLD_PYTHON_VERSION from test_gradle_plugin. The available versions on each
        # runner are listed at
        # https://github.com/actions/python-versions/blob/main/versions-manifest.json.
        python-version: |
          3.7
          3.8
          3.9
          ${{ steps.python-default.outputs.full-version }}
          3.11
          3.12
          3.13
        allow-prereleases: true

outputs:
  python-default:
    description: Command to run the default Python version
    value: ${{ steps.python-default.outputs.command }}
