name: Setup Python
description:

# The available Python versions on each runner are listed at
# https://github.com/actions/python-versions/blob/main/versions-manifest.json.
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5.1.0
      with:
        # This should include all major.minor versions supported by the runtime, plus
        # OLD_PYTHON_VERSION from test_gradle_plugin.
        python-version: |
          3.7
          3.10
          3.11
          3.12
          3.13
        allow-prereleases: true

    - name: Get default Python version
      id: python-default
      shell: bash
      run: |
        version=$(target/list_versions.py --default)
        (
            if [ $RUNNER_OS = Windows ]; then
                echo "command=py -$version"
            else
                echo "command=python$version"
            fi
        ) >> $GITHUB_OUTPUT

outputs:
  python-default:
    description: Command to run the default Python version
    value: ${{ steps.python-default.outputs.command }}
