name: Setup Python
description:

inputs:
  extra-versions:
    description: |
      Additional versions to install, on top of the supported runtime versions. One
      version per line, in the same syntax as the standard setup-python action.

runs:
  using: composite
  steps:
    - name: List runtime versions
      id: runtime-versions
      shell: bash
      run: |
        (
            echo "versions<<EOF"
            target/list-versions.py --short
            echo EOF
        ) >> $GITHUB_OUTPUT

    - uses: actions/setup-python@v4.6.1
      with:
        python-version: |
          ${{ steps.runtime-versions.outputs.versions }}
          ${{ inputs.extra-versions }}

    - name: Set default Python command
      id: python-default
      shell: bash
      run: |
        version=$(target/list-versions.py --default)
        if [ $RUNNER_OS = Windows ]; then
            echo "command=py -$version"
        else
            echo "command=python$version"
        fi >> $GITHUB_OUTPUT

outputs:
  python-default:
    description: Command to run the default Python version
    value: ${{ steps.python-default.outputs.command }}
