# The 4 OpenCV packages are mostly the same, so most changes to one should also be done to the
# others.
package:
  name: opencv-python
  version: "4.11.0.86"

build:
  number: 2

requirements:
  build:
    - cmake 3.22
    - scikit-build 0.14.0
  host:
    - chaquopy-libgfortran 4.9
    - chaquopy-libpng 1.6.34
    - chaquopy-libjpeg 1.5.3
    - chaquopy-openblas 0.2.20
    - numpy 1.26.2
    - python
