{% if PY_VER == "3.8" %}
    {% set openssl_suffix = "" %}
{% else %}
   {% set openssl_suffix = "-openssl-3" %}
{% endif %}

package:
  name: pycurl
  version: 7.43.0.6

build:
  number: 2

requirements:
  host:
    - chaquopy-curl{{ openssl_suffix }} 7.76.1
    - openssl
