export PATH='/Users/rkm/beeware/chaquopy/server/pypi/env/bin:/Users/rkm/beeware/chaquopy/server/pypi/packages/zstandard/build/0.15.2/cp38-cp38-ios_12_0_iphoneos_arm64/requirements/opt/bin:/Users/rkm/beeware/chaquopy/venv3.8/bin:/Users/rkm/.nvm/versions/node/v16.14.2/bin:/Users/rkm/.rbenv/shims:/Library/Frameworks/Python.framework/Versions/3.11/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/rkm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/rkm/.local/bin:/Users/rkm/.local/bin'
export PYTHONPATH='/Users/rkm/beeware/chaquopy/server/pypi/env/lib/python:/Users/rkm/beeware/chaquopy/server/pypi/packages/zstandard/build/0.15.2/cp38-cp38-ios_12_0_iphoneos_arm64/requirements'
export CROSS_COMPILE_PLATFORM='ios'
export CROSS_COMPILE_PLATFORM_TAG='iOS_12.0_iphoneos_arm64'
export CROSS_COMPILE_PREFIX='/Users/rkm/beeware/chaquopy/server/pypi/support/3.8/Python.xcframework/ios-arm64'
export CROSS_COMPILE_IMPLEMENTATION='iphoneos_arm64'
export CROSS_COMPILE_SDK_ROOT='/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.0.sdk'
export CROSS_COMPILE_TOOLCHAIN_SLICE='ios-arm64'
export CROSS_COMPILE_SYSCONFIGDATA='/Users/rkm/beeware/chaquopy/server/pypi/support/3.8/python-stdlib/_sysconfigdata__ios_iphoneos_arm64.py'
export AR='xcrun --sdk iphoneos ar'
export ARFLAGS='rcs'
export BLDSHARED='xcrun --sdk iphoneos clang -bundle -undefined dynamic_lookup -target arm64-apple-ios --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.0.sdk -mios-version-min=12.0'
export CFLAGS='-Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -target arm64-apple-ios --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.0.sdk -mios-version-min=12.0 -idirafter /Users/rkm/beeware/chaquopy/server/pypi/support/3.8/Python.xcframework/ios-arm64/Headers'
export CC='xcrun --sdk iphoneos clang'
export CXX='xcrun --sdk iphoneos clang'
export CONFIGURE_CFLAGS='-target arm64-apple-ios --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.0.sdk -mios-version-min=12.0'
export CONFIGURE_LDFLAGS='-target arm64-apple-ios --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.0.sdk -mios-version-min=12.0'
export LDFLAGS='-target arm64-apple-ios --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.0.sdk -mios-version-min=12.0'
export LDSHARED='xcrun --sdk iphoneos clang -bundle -undefined dynamic_lookup -target arm64-apple-ios --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.0.sdk -mios-version-min=12.0'
export HOST_TRIPLET='arm64-apple-ios'
export CHAQUOPY_ABI='iphoneos_arm64'
export CHAQUOPY_PYTHON='3.8'
export CHAQUOPY_TRIPLET='aarch64-apple-darwin'
export CPU_COUNT='10'
export PKG_BUILDNUM='0'
export PKG_NAME='zstandard'
export PKG_VERSION='0.15.2'
export RECIPE_DIR='/Users/rkm/beeware/chaquopy/server/pypi/packages/zstandard'
export SRC_DIR='/Users/rkm/beeware/chaquopy/server/pypi/packages/zstandard/'

cd build/0.15.2/cp38-cp38-ios_12_0_iphoneos_arm64/src
python setup.py build_ext