package:
  name: pyzmq
  # When updating, check the libzmq version in the sdist's buildutils/bundle.py, and
  # consider updating chaquopy-libzmq as well, and changing the host requirement below.
  version: "24.0.1"

build:
  number: 1

requirements:
  build:
    - packaging 22.0
  host:
    - chaquopy-libzmq 4.3.4
