# See notes in google-crc32c/meta.yaml.
{% set version = "1.1.2" %}

package:
  name: chaquopy-crc32c
  version: {{ version }}

build:
  number: 1

source:
  git_url: https://github.com/google/crc32c
  git_rev: {{ version }}

requirements:
  build:
    - cmake 3.28.1
